### ISSUE TITLE
In that train.py script i got an issue regarding  eval() missing 1 required positional argument: 'fake_dir' how to solve it i tried out so many things but its not working

### ISSUE THREAD

**Issue by soumyajee** [MarkHershey/AudioDeepFakeDetection#3]

**Comment by MarkHershey** [comment]
How did you execute the script? What have you tried? What are the outputs? You need to provide more information.

**Comment by soumyajee** [comment]
i put ljspeech wavefave dataset as per as required in fake and real folder
then i try to run train.py files i got following error:

**Comment by soumyajee** [comment]
I go through the terminal and run python train.py file and i got the following issue after giving the real dataset and fake dataset path such as 
real_dir=data/real/wavs",
fake_dir=data/fake/generated_audio/ljspeech_melgan
and i got the following error :
![Screenshot from 2022-12-28 10-03-51](https://user-images.githubusercontent.com/79016133/209766413-abbcab17-d952-4049-93f6-c1aa620d8313.png)
2022-12-28 11:33:55,219 - INFO - Batch size: 256, seed: None, epochs: 20
>>>>> Experiment Failed: ShallowCNN_lfcc_I


2022-12-28 11:33:55,219 - ERROR - eval() missing 1 required positional argument: 'fake_dir'
Traceback (most recent call last):
  File "/home/soumya/deepfake_detection/AudioDeepFakeDetection/train.py", line 599, in main
    experiment(
  File "/home/soumya/deepfake_detection/AudioDeepFakeDetection/train.py", line 447, in experiment
    train(
  File "/home/soumya/deepfake_detection/AudioDeepFakeDetection/train.py", line 143, in train
    Model = eval(model_classname)
TypeError: eval() missing 1 required positional argument: 'fake_dir'

**Comment by MarkHershey** [comment]
Hi @soumyajee, thanks for the info. The exception is due to a bug in my `train.py` indeed, there was a conflict between my custom function `eval()` and Python's built-in function `eval()`. At line 143, where your error occurred, I intended to use the built-in `eval()`. 

I have committed a [fix](https://github.com/MarkHershey/AudioDeepFakeDetection/commit/e40ad0cee5e5ab29f96227e99ca3c1e3fae611a3) to this bug in the master branch, please use the latest code to run again.

**Comment by soumyajee** [comment]
Again i got the following issue while running trin.py file:
2022-12-29 16:54:21,966 - ERROR - 
Traceback (most recent call last):
  File "/home/soumya/deepfake_detection/AudioDeepFakeDetection/train.py", line 599, in main
    experiment(
  File "/home/soumya/deepfake_detection/AudioDeepFakeDetection/train.py", line 447, in experiment
    train(
  File "/home/soumya/deepfake_detection/AudioDeepFakeDetection/train.py", line 165, in train
    assert melgan_dir.is_dir()
AssertionError
![Screenshot from 2022-12-29 16-55-05](https://user-images.githubusercontent.com/79016133/209944696-fa9bb2fe-3528-43f6-bdaa-3a5120177157.png)

**Comment by MarkHershey** [comment]
> Again i got the following issue while running trin.py file: 2022-12-29 16:54:21,966 - ERROR - Traceback (most recent call last): File "/home/soumya/deepfake_detection/AudioDeepFakeDetection/train.py", line 599, in main experiment( File "/home/soumya/deepfake_detection/AudioDeepFakeDetection/train.py", line 447, in experiment train( File "/home/soumya/deepfake_detection/AudioDeepFakeDetection/train.py", line 165, in train assert melgan_dir.is_dir() AssertionError ![Screenshot from 2022-12-29 16-55-05](https://user-images.githubusercontent.com/79016133/209944696-fa9bb2fe-3528-43f6-bdaa-3a5120177157.png)

Can you run `python train.py --debug_all` and see what the result is?

**Comment by soumyajee** [comment]
I got the following issue while running train.py --debug_all its following:
Traceback (most recent call last):
  File "/home/soumya/deepfake_detection/AudioDeepFakeDetection/train.py", line 621, in <module>
    main()
  File "/home/soumya/deepfake_detection/AudioDeepFakeDetection/train.py", line 589, in main
    debug(args.real, args.fake, args.device)
AttributeError: 'Namespace' object has no attribute 'real'
![Screenshot from 2022-12-30 10-09-03](https://user-images.githubusercontent.com/79016133/210035099-2866cbd3-6742-436f-bde7-76e7cfd898b4.png)

**Comment by MarkHershey** [comment]
@soumyajee you are not using my latest code, this issue has been fixed

**Comment by soumyajee** [comment]
Thanks for ur support we have already solve that issue now our scripts running fine
