### ISSUE TITLE
Can I use my own voice clip?

### ISSUE THREAD

**Issue by Miapata** [MarkHershey/AudioDeepFakeDetection#4]
I was wondering if after I trained my data, is it possible to use my own voice clip to detect if it is fake or not?

**Comment by MarkHershey** [comment]
of course, however, my code currently does not provide this function, you need to study a bit on how this code works and write your own function that supports taking in a single voice clip for inference with batch size 1.

**Comment by Miapata** [comment]
Okay I was looking through the code and the closest thing I found was in the Trainer.py file. Maybe I'm off. I'll try to create one and study a bit more. I also would appreciate your help with this. Thank you 🙂

**Comment by azazar** [comment]
Did you succeed? Would you share the result?
