### ISSUE TITLE
Given the model and a audio file, print real or fake voice

### ISSUE THREAD

**Issue by Epanhua622** [MarkHershey/AudioDeepFakeDetection#9]
I have been trying to use your model in the google drive (best.pt) model and tried to preprocess it however I keep getting different types of errors whenever I try changing something. Such as:

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x241152 and 15104x128)
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 1, 1, 40, 64600]

I am trying to do something just like your website where given the audio it displays real or fake. Is there any code or reference?

**Comment by MarkHershey** [comment]
I believe there is a [fork](https://github.com/PlayerBerny12/AudioDeepFakeDetection) of this repo that has implemented single audio file testing, you may want to refer to their [implementation](https://github.com/PlayerBerny12/AudioDeepFakeDetection/blob/9de23dbf6052000f112ee793e4c00db23a957f6f/train.py#L391). Disclaimer: I haven't checked or run their code.
